### ISSUE TITLE
scanner crashes with ImageFormat error on latest mlkit versions on Android

### ISSUE THREAD

**Issue by smallTrogdor** [SchweizerischeBundesbahnen/data-scanner-flutter#9]
### Current Behavior

Using the scanner with versions of ml kit starting from:

```yaml
  # https://pub.dev/packages/google_mlkit_text_recognition
  google_mlkit_text_recognition: ^0.13.0
  # https://pub.dev/packages/google_mlkit_barcode_scanning
  google_mlkit_barcode_scanning: ^0.12.0
```

**and** 

```yaml
  # https://pub.dev/packages/camera
  camera: ^0.11.0
```

crashes in the mlkit text_recognition scanImage method on some Android devices (including Standard SBB employee devices).

The specific error is an ImageFormat error (related to nv21 vs. yuv420).

### Expected Behavior

The scanner works without crashes.

### Steps To Reproduce

Run example app with above specified dependencies

### On which OS do you experience this bug?

Android

### OS Version

Any

### Flutter SDK version

Any
